### ISSUE TITLE
Setup Process for Contribution Survey

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Documentation#16]
## Goal
In regards to the Mindfulness Policy, it is important to survey contribution data from contributors (mandatory!)

## Dependencies
#10 

## Specifications
Draft can be found [**HERE**](https://github.com/SecretDecks/Documentation/blob/main/Draft-DAO-Contribution-Survey.md)

1. Draft
2. Discuss
3. Document results
3. Apply edits if needed
4. Vote on final approval
5. Publish in SD github repository

**Comment by DanM3rcurius** [comment]
I propose the following process:
1. forking of SecretDecks/Documentation repo
2. rename "Template-Contribution-Survey.md" to "<your_name/pseudonym-Contribution-Survey.md> 
3. editing "<your_name/pseudonym-Contribution-Survey.md> 
4. requesting PR with review by at least two other founding core members

@stephen-rowan @wlstylr @evolayak What do you think?

**Comment by evolayak** [comment]
@DanM3rcurius, @stephen-rowan and @wlstylr - sounds good to me!

**Comment by wlstylr** [comment]
@DanM3rcurius @stephen-rowan @wlstylr 

I agree, this works for me.  We may want to create a screencast video of how this process works as an example for those unfamiliar.

**Comment by stephen-rowan** [comment]
Good system Dan - but ideally this should be done on a regular basis (possibly every month ?) - so that member contributions can be tracked and rewarded in the medium term. (Until this can be replaced by a DID app). 

A simple way to do this would to be add a date prefix to "Dan-Contribution-Survey.md" e.g. "2021-05-31-Dan-Contribution-Survey.md"" (end of May). (so it orders by date).

If "In review" then this should be written at the top of the document as a headline and changed to "merged" or "approved" once completed.

**Comment by DanM3rcurius** [comment]
> Inspired by Dan's contribution process, I have created a Custom Issue Template for Contributions. I have recorded a rough screen-cast of how this would work below ...
> 
>  Contribution.Survey.mp4 
> I can set-up a Custom Issue Template for Contributions for SecretDecks if everyone likes this process.
> 

You are incredible @stephen-rowan 🧙🏿‍♂️💫 This makes it super easy and everyone can find those 120 seconds a month to do this quick step! 
And again I learnt something new about issue templates 🥰🙏 Thank you!!!

**Comment by stephen-rowan** [comment]
Cool - @DanM3rcurius - you need Admin rights to setup GitHub Issue Templates ([this is a useful YouTube tutorial ](https://www.youtube.com/watch?v=UPsCXqxxJUA)) on how to do it.

Call it something like "SecretDecks Contributions Survey". And paste the markdown you want from [Template-Contribution-Survey](https://github.com/SecretDecks/Documentation/blob/main/Template-Contribution-Survey.md). 

I altered the Issue Template Title to 2021-[Month]-[Day]-{Name]-Contribution-Survey - to prompt for user input. Here is an example [Contribution Issue](https://github.com/Quality-Assurance-DAO/DAO-Open-Source/issues/32) on the QA-DAO repo.

S

**Comment by DanM3rcurius** [comment]
template is setup here:
https://github.com/SecretDecks/Documentation/issues/new/choose

I'll add a likn to the main readme file in the repo and will talk about it in todays meeting as well!

**Comment by stephen-rowan** [comment]
Hi Dan, 

I would cut down the explanatory text and CC License by just providing a link to a detailed explanation for those who need it. 
Just leave what absolutely needs to be completed.
You can also add a label in the Issue Template - e.g. "Contribution Survey" - so that they can easily be filtered.

S

**Comment by DanM3rcurius** [comment]
> Hi Dan,
> 
> I would cut out the explanatory text and CC License by just providing a link to a detailed explanation for those who need it.
> Just leave what absolutely needs to be completed.
> You can also add a label in the Issue Template - e.g. "Contribution Survey" - so that they can easily be filtered.
> 
> S

thanks for doing this; PR is merged  and I'll close the issue now!
